<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2031" started-at="2020-05-14T22:01:24 EDT" finished-at="2020-05-14T22:01:26 EDT">
    <groups>
    </groups>
    <test name="Test" duration-ms="2031" started-at="2020-05-14T22:01:24 EDT" finished-at="2020-05-14T22:01:26 EDT">
      <class name="gtplBank_SignIn.LoginTest2">
        <test-method status="FAIL" signature="titleTest2()[pri:1, instance:gtplBank_SignIn.LoginTest2@64729b1e]" name="titleTest2" duration-ms="11" started-at="2020-05-14T22:01:25 EDT" finished-at="2020-05-14T22:01:25 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GTPL Bank  Page] but found [GTPL Bank Home Page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GTPL Bank  Page] but found [GTPL Bank Home Page]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at gtplBank_SignIn.LoginTest2.titleTest2(LoginTest2.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:gtplBank_SignIn.LoginTest2@64729b1e]" name="getResult" is-config="true" duration-ms="926" started-at="2020-05-14T22:01:25 EDT" finished-at="2020-05-14T22:01:26 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=titleTest2 status=FAILURE method=LoginTest2.titleTest2()[pri:1, instance:gtplBank_SignIn.LoginTest2@64729b1e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="UrlTest2()[pri:2, instance:gtplBank_SignIn.LoginTest2@64729b1e]" name="UrlTest2" duration-ms="6" started-at="2020-05-14T22:01:26 EDT" finished-at="2020-05-14T22:01:26 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UrlTest2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:gtplBank_SignIn.LoginTest2@64729b1e]" name="getResult" is-config="true" duration-ms="1" started-at="2020-05-14T22:01:26 EDT" finished-at="2020-05-14T22:01:26 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UrlTest2 status=SUCCESS method=LoginTest2.UrlTest2()[pri:2, instance:gtplBank_SignIn.LoginTest2@64729b1e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="login2()[pri:3, instance:gtplBank_SignIn.LoginTest2@64729b1e]" name="login2" duration-ms="204" started-at="2020-05-14T22:01:26 EDT" finished-at="2020-05-14T22:01:26 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:gtplBank_SignIn.LoginTest2@64729b1e]" name="getResult" is-config="true" duration-ms="1" started-at="2020-05-14T22:01:26 EDT" finished-at="2020-05-14T22:01:26 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login2 status=SUCCESS method=LoginTest2.login2()[pri:3, instance:gtplBank_SignIn.LoginTest2@64729b1e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- gtplBank_SignIn.LoginTest2 -->
      <class name="gtplBank_SignIn.LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="setup" is-config="true" duration-ms="5654" started-at="2020-05-14T22:01:18 EDT" finished-at="2020-05-14T22:01:24 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="titleTest()[pri:1, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="titleTest" duration-ms="71" started-at="2020-05-14T22:01:24 EDT" finished-at="2020-05-14T22:01:24 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GTPL Bank  Page] but found [GTPL Bank Home Page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GTPL Bank  Page] but found [GTPL Bank Home Page]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at gtplBank_SignIn.LoginTest.titleTest(LoginTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="getResult" is-config="true" duration-ms="461" started-at="2020-05-14T22:01:24 EDT" finished-at="2020-05-14T22:01:25 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=titleTest status=FAILURE method=LoginTest.titleTest()[pri:1, instance:gtplBank_SignIn.LoginTest@4e7dc304] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="UrlTest()[pri:2, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="UrlTest" duration-ms="6" started-at="2020-05-14T22:01:25 EDT" finished-at="2020-05-14T22:01:25 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UrlTest -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="getResult" is-config="true" duration-ms="0" started-at="2020-05-14T22:01:25 EDT" finished-at="2020-05-14T22:01:25 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UrlTest status=SUCCESS method=LoginTest.UrlTest()[pri:2, instance:gtplBank_SignIn.LoginTest@4e7dc304] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="login()[pri:3, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="login" duration-ms="311" started-at="2020-05-14T22:01:25 EDT" finished-at="2020-05-14T22:01:25 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="getResult" is-config="true" duration-ms="0" started-at="2020-05-14T22:01:25 EDT" finished-at="2020-05-14T22:01:25 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=SUCCESS method=LoginTest.login()[pri:3, instance:gtplBank_SignIn.LoginTest@4e7dc304] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:gtplBank_SignIn.LoginTest@4e7dc304]" name="tearDown" is-config="true" duration-ms="1919" started-at="2020-05-14T22:01:26 EDT" finished-at="2020-05-14T22:01:28 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- gtplBank_SignIn.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
